spring.application.name=ms-capacidad
server.port=8081

# R2DBC MySQL
spring.r2dbc.url=r2dbc:mysql://localhost:3307/db_capacidad
spring.r2dbc.username=root
spring.r2dbc.password=root

# External services
external.technology-service.url=http://localhost:8080

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
